import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import Header from "./components/Header";
import { createClient } from "./utils/supabase/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  
     const supabase = await createClient()
     const { data } = await supabase.auth.getUser()

     
  
  return (
    <html lang="en">
      <body className={` ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {data?.user && <Header />}
        <div className="container mx-auto p-6">
          {children}
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
